//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace VoyIteso.ServiceReferenceVoyItesoMovil {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://prueba.iteso.mx/", ConfigurationName="ServiceReferenceVoyItesoMovil.VoyItesoMovil")]
    public interface VoyItesoMovil {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://prueba.iteso.mx/VoyItesoMovil/GetRouteInfoRequest", ReplyAction="http://prueba.iteso.mx/VoyItesoMovil/GetRouteInfoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginGetRouteInfo(VoyIteso.ServiceReferenceVoyItesoMovil.GetRouteInfoRequest request, System.AsyncCallback callback, object asyncState);
        
        VoyIteso.ServiceReferenceVoyItesoMovil.GetRouteInfoResponse EndGetRouteInfo(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://prueba.iteso.mx/VoyItesoMovil/GetUserNameRequest", ReplyAction="http://prueba.iteso.mx/VoyItesoMovil/GetUserNameResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginGetUserName(VoyIteso.ServiceReferenceVoyItesoMovil.GetUserNameRequest request, System.AsyncCallback callback, object asyncState);
        
        VoyIteso.ServiceReferenceVoyItesoMovil.GetUserNameResponse EndGetUserName(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://prueba.iteso.mx/VoyItesoMovil/GetRouteSearchResultRequest", ReplyAction="http://prueba.iteso.mx/VoyItesoMovil/GetRouteSearchResultResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginGetRouteSearchResult(VoyIteso.ServiceReferenceVoyItesoMovil.GetRouteSearchResultRequest request, System.AsyncCallback callback, object asyncState);
        
        VoyIteso.ServiceReferenceVoyItesoMovil.GetRouteSearchResultResponse EndGetRouteSearchResult(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://prueba.iteso.mx/VoyItesoMovil/GetPersonImageRequest", ReplyAction="http://prueba.iteso.mx/VoyItesoMovil/GetPersonImageResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginGetPersonImage(VoyIteso.ServiceReferenceVoyItesoMovil.GetPersonImageRequest request, System.AsyncCallback callback, object asyncState);
        
        VoyIteso.ServiceReferenceVoyItesoMovil.GetPersonImageResponse EndGetPersonImage(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRouteInfo", WrapperNamespace="http://prueba.iteso.mx/", IsWrapped=true)]
    public partial class GetRouteInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prueba.iteso.mx/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prueba.iteso.mx/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idRuta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prueba.iteso.mx/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPerfil;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prueba.iteso.mx/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPersona;
        
        public GetRouteInfoRequest() {
        }
        
        public GetRouteInfoRequest(string token, int idRuta, int idPerfil, int idPersona) {
            this.token = token;
            this.idRuta = idRuta;
            this.idPerfil = idPerfil;
            this.idPersona = idPersona;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRouteInfoResponse", WrapperNamespace="http://prueba.iteso.mx/", IsWrapped=true)]
    public partial class GetRouteInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prueba.iteso.mx/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] @return;
        
        public GetRouteInfoResponse() {
        }
        
        public GetRouteInfoResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserName", WrapperNamespace="http://prueba.iteso.mx/", IsWrapped=true)]
    public partial class GetUserNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prueba.iteso.mx/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token;
        
        public GetUserNameRequest() {
        }
        
        public GetUserNameRequest(string token) {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserNameResponse", WrapperNamespace="http://prueba.iteso.mx/", IsWrapped=true)]
    public partial class GetUserNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prueba.iteso.mx/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public GetUserNameResponse() {
        }
        
        public GetUserNameResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRouteSearchResult", WrapperNamespace="http://prueba.iteso.mx/", IsWrapped=true)]
    public partial class GetRouteSearchResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prueba.iteso.mx/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prueba.iteso.mx/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string queryString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prueba.iteso.mx/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int fuma;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prueba.iteso.mx/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string genero;
        
        public GetRouteSearchResultRequest() {
        }
        
        public GetRouteSearchResultRequest(string token, string queryString, int fuma, string genero) {
            this.token = token;
            this.queryString = queryString;
            this.fuma = fuma;
            this.genero = genero;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRouteSearchResultResponse", WrapperNamespace="http://prueba.iteso.mx/", IsWrapped=true)]
    public partial class GetRouteSearchResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prueba.iteso.mx/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public GetRouteSearchResultResponse() {
        }
        
        public GetRouteSearchResultResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPersonImage", WrapperNamespace="http://prueba.iteso.mx/", IsWrapped=true)]
    public partial class GetPersonImageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prueba.iteso.mx/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prueba.iteso.mx/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idRuta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prueba.iteso.mx/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPerfil;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prueba.iteso.mx/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPersona;
        
        public GetPersonImageRequest() {
        }
        
        public GetPersonImageRequest(string token, int idRuta, int idPerfil, int idPersona) {
            this.token = token;
            this.idRuta = idRuta;
            this.idPerfil = idPerfil;
            this.idPersona = idPersona;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPersonImageResponse", WrapperNamespace="http://prueba.iteso.mx/", IsWrapped=true)]
    public partial class GetPersonImageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prueba.iteso.mx/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] @return;
        
        public GetPersonImageResponse() {
        }
        
        public GetPersonImageResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VoyItesoMovilChannel : VoyIteso.ServiceReferenceVoyItesoMovil.VoyItesoMovil, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetRouteInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetRouteInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetUserNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetUserNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetRouteSearchResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetRouteSearchResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPersonImageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetPersonImageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public byte[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VoyItesoMovilClient : System.ServiceModel.ClientBase<VoyIteso.ServiceReferenceVoyItesoMovil.VoyItesoMovil>, VoyIteso.ServiceReferenceVoyItesoMovil.VoyItesoMovil {
        
        private BeginOperationDelegate onBeginGetRouteInfoDelegate;
        
        private EndOperationDelegate onEndGetRouteInfoDelegate;
        
        private System.Threading.SendOrPostCallback onGetRouteInfoCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetUserNameDelegate;
        
        private EndOperationDelegate onEndGetUserNameDelegate;
        
        private System.Threading.SendOrPostCallback onGetUserNameCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetRouteSearchResultDelegate;
        
        private EndOperationDelegate onEndGetRouteSearchResultDelegate;
        
        private System.Threading.SendOrPostCallback onGetRouteSearchResultCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetPersonImageDelegate;
        
        private EndOperationDelegate onEndGetPersonImageDelegate;
        
        private System.Threading.SendOrPostCallback onGetPersonImageCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public VoyItesoMovilClient() {
        }
        
        public VoyItesoMovilClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VoyItesoMovilClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VoyItesoMovilClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VoyItesoMovilClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetRouteInfoCompletedEventArgs> GetRouteInfoCompleted;
        
        public event System.EventHandler<GetUserNameCompletedEventArgs> GetUserNameCompleted;
        
        public event System.EventHandler<GetRouteSearchResultCompletedEventArgs> GetRouteSearchResultCompleted;
        
        public event System.EventHandler<GetPersonImageCompletedEventArgs> GetPersonImageCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult VoyIteso.ServiceReferenceVoyItesoMovil.VoyItesoMovil.BeginGetRouteInfo(VoyIteso.ServiceReferenceVoyItesoMovil.GetRouteInfoRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetRouteInfo(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetRouteInfo(string token, int idRuta, int idPerfil, int idPersona, System.AsyncCallback callback, object asyncState) {
            VoyIteso.ServiceReferenceVoyItesoMovil.GetRouteInfoRequest inValue = new VoyIteso.ServiceReferenceVoyItesoMovil.GetRouteInfoRequest();
            inValue.token = token;
            inValue.idRuta = idRuta;
            inValue.idPerfil = idPerfil;
            inValue.idPersona = idPersona;
            return ((VoyIteso.ServiceReferenceVoyItesoMovil.VoyItesoMovil)(this)).BeginGetRouteInfo(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VoyIteso.ServiceReferenceVoyItesoMovil.GetRouteInfoResponse VoyIteso.ServiceReferenceVoyItesoMovil.VoyItesoMovil.EndGetRouteInfo(System.IAsyncResult result) {
            return base.Channel.EndGetRouteInfo(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string[] EndGetRouteInfo(System.IAsyncResult result) {
            VoyIteso.ServiceReferenceVoyItesoMovil.GetRouteInfoResponse retVal = ((VoyIteso.ServiceReferenceVoyItesoMovil.VoyItesoMovil)(this)).EndGetRouteInfo(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBeginGetRouteInfo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string token = ((string)(inValues[0]));
            int idRuta = ((int)(inValues[1]));
            int idPerfil = ((int)(inValues[2]));
            int idPersona = ((int)(inValues[3]));
            return this.BeginGetRouteInfo(token, idRuta, idPerfil, idPersona, callback, asyncState);
        }
        
        private object[] OnEndGetRouteInfo(System.IAsyncResult result) {
            string[] retVal = this.EndGetRouteInfo(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetRouteInfoCompleted(object state) {
            if ((this.GetRouteInfoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetRouteInfoCompleted(this, new GetRouteInfoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetRouteInfoAsync(string token, int idRuta, int idPerfil, int idPersona) {
            this.GetRouteInfoAsync(token, idRuta, idPerfil, idPersona, null);
        }
        
        public void GetRouteInfoAsync(string token, int idRuta, int idPerfil, int idPersona, object userState) {
            if ((this.onBeginGetRouteInfoDelegate == null)) {
                this.onBeginGetRouteInfoDelegate = new BeginOperationDelegate(this.OnBeginGetRouteInfo);
            }
            if ((this.onEndGetRouteInfoDelegate == null)) {
                this.onEndGetRouteInfoDelegate = new EndOperationDelegate(this.OnEndGetRouteInfo);
            }
            if ((this.onGetRouteInfoCompletedDelegate == null)) {
                this.onGetRouteInfoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetRouteInfoCompleted);
            }
            base.InvokeAsync(this.onBeginGetRouteInfoDelegate, new object[] {
                        token,
                        idRuta,
                        idPerfil,
                        idPersona}, this.onEndGetRouteInfoDelegate, this.onGetRouteInfoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult VoyIteso.ServiceReferenceVoyItesoMovil.VoyItesoMovil.BeginGetUserName(VoyIteso.ServiceReferenceVoyItesoMovil.GetUserNameRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetUserName(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetUserName(string token, System.AsyncCallback callback, object asyncState) {
            VoyIteso.ServiceReferenceVoyItesoMovil.GetUserNameRequest inValue = new VoyIteso.ServiceReferenceVoyItesoMovil.GetUserNameRequest();
            inValue.token = token;
            return ((VoyIteso.ServiceReferenceVoyItesoMovil.VoyItesoMovil)(this)).BeginGetUserName(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VoyIteso.ServiceReferenceVoyItesoMovil.GetUserNameResponse VoyIteso.ServiceReferenceVoyItesoMovil.VoyItesoMovil.EndGetUserName(System.IAsyncResult result) {
            return base.Channel.EndGetUserName(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGetUserName(System.IAsyncResult result) {
            VoyIteso.ServiceReferenceVoyItesoMovil.GetUserNameResponse retVal = ((VoyIteso.ServiceReferenceVoyItesoMovil.VoyItesoMovil)(this)).EndGetUserName(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBeginGetUserName(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string token = ((string)(inValues[0]));
            return this.BeginGetUserName(token, callback, asyncState);
        }
        
        private object[] OnEndGetUserName(System.IAsyncResult result) {
            string retVal = this.EndGetUserName(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetUserNameCompleted(object state) {
            if ((this.GetUserNameCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetUserNameCompleted(this, new GetUserNameCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetUserNameAsync(string token) {
            this.GetUserNameAsync(token, null);
        }
        
        public void GetUserNameAsync(string token, object userState) {
            if ((this.onBeginGetUserNameDelegate == null)) {
                this.onBeginGetUserNameDelegate = new BeginOperationDelegate(this.OnBeginGetUserName);
            }
            if ((this.onEndGetUserNameDelegate == null)) {
                this.onEndGetUserNameDelegate = new EndOperationDelegate(this.OnEndGetUserName);
            }
            if ((this.onGetUserNameCompletedDelegate == null)) {
                this.onGetUserNameCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetUserNameCompleted);
            }
            base.InvokeAsync(this.onBeginGetUserNameDelegate, new object[] {
                        token}, this.onEndGetUserNameDelegate, this.onGetUserNameCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult VoyIteso.ServiceReferenceVoyItesoMovil.VoyItesoMovil.BeginGetRouteSearchResult(VoyIteso.ServiceReferenceVoyItesoMovil.GetRouteSearchResultRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetRouteSearchResult(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetRouteSearchResult(string token, string queryString, int fuma, string genero, System.AsyncCallback callback, object asyncState) {
            VoyIteso.ServiceReferenceVoyItesoMovil.GetRouteSearchResultRequest inValue = new VoyIteso.ServiceReferenceVoyItesoMovil.GetRouteSearchResultRequest();
            inValue.token = token;
            inValue.queryString = queryString;
            inValue.fuma = fuma;
            inValue.genero = genero;
            return ((VoyIteso.ServiceReferenceVoyItesoMovil.VoyItesoMovil)(this)).BeginGetRouteSearchResult(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VoyIteso.ServiceReferenceVoyItesoMovil.GetRouteSearchResultResponse VoyIteso.ServiceReferenceVoyItesoMovil.VoyItesoMovil.EndGetRouteSearchResult(System.IAsyncResult result) {
            return base.Channel.EndGetRouteSearchResult(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGetRouteSearchResult(System.IAsyncResult result) {
            VoyIteso.ServiceReferenceVoyItesoMovil.GetRouteSearchResultResponse retVal = ((VoyIteso.ServiceReferenceVoyItesoMovil.VoyItesoMovil)(this)).EndGetRouteSearchResult(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBeginGetRouteSearchResult(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string token = ((string)(inValues[0]));
            string queryString = ((string)(inValues[1]));
            int fuma = ((int)(inValues[2]));
            string genero = ((string)(inValues[3]));
            return this.BeginGetRouteSearchResult(token, queryString, fuma, genero, callback, asyncState);
        }
        
        private object[] OnEndGetRouteSearchResult(System.IAsyncResult result) {
            string retVal = this.EndGetRouteSearchResult(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetRouteSearchResultCompleted(object state) {
            if ((this.GetRouteSearchResultCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetRouteSearchResultCompleted(this, new GetRouteSearchResultCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetRouteSearchResultAsync(string token, string queryString, int fuma, string genero) {
            this.GetRouteSearchResultAsync(token, queryString, fuma, genero, null);
        }
        
        public void GetRouteSearchResultAsync(string token, string queryString, int fuma, string genero, object userState) {
            if ((this.onBeginGetRouteSearchResultDelegate == null)) {
                this.onBeginGetRouteSearchResultDelegate = new BeginOperationDelegate(this.OnBeginGetRouteSearchResult);
            }
            if ((this.onEndGetRouteSearchResultDelegate == null)) {
                this.onEndGetRouteSearchResultDelegate = new EndOperationDelegate(this.OnEndGetRouteSearchResult);
            }
            if ((this.onGetRouteSearchResultCompletedDelegate == null)) {
                this.onGetRouteSearchResultCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetRouteSearchResultCompleted);
            }
            base.InvokeAsync(this.onBeginGetRouteSearchResultDelegate, new object[] {
                        token,
                        queryString,
                        fuma,
                        genero}, this.onEndGetRouteSearchResultDelegate, this.onGetRouteSearchResultCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult VoyIteso.ServiceReferenceVoyItesoMovil.VoyItesoMovil.BeginGetPersonImage(VoyIteso.ServiceReferenceVoyItesoMovil.GetPersonImageRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetPersonImage(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetPersonImage(string token, int idRuta, int idPerfil, int idPersona, System.AsyncCallback callback, object asyncState) {
            VoyIteso.ServiceReferenceVoyItesoMovil.GetPersonImageRequest inValue = new VoyIteso.ServiceReferenceVoyItesoMovil.GetPersonImageRequest();
            inValue.token = token;
            inValue.idRuta = idRuta;
            inValue.idPerfil = idPerfil;
            inValue.idPersona = idPersona;
            return ((VoyIteso.ServiceReferenceVoyItesoMovil.VoyItesoMovil)(this)).BeginGetPersonImage(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VoyIteso.ServiceReferenceVoyItesoMovil.GetPersonImageResponse VoyIteso.ServiceReferenceVoyItesoMovil.VoyItesoMovil.EndGetPersonImage(System.IAsyncResult result) {
            return base.Channel.EndGetPersonImage(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private byte[] EndGetPersonImage(System.IAsyncResult result) {
            VoyIteso.ServiceReferenceVoyItesoMovil.GetPersonImageResponse retVal = ((VoyIteso.ServiceReferenceVoyItesoMovil.VoyItesoMovil)(this)).EndGetPersonImage(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBeginGetPersonImage(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string token = ((string)(inValues[0]));
            int idRuta = ((int)(inValues[1]));
            int idPerfil = ((int)(inValues[2]));
            int idPersona = ((int)(inValues[3]));
            return this.BeginGetPersonImage(token, idRuta, idPerfil, idPersona, callback, asyncState);
        }
        
        private object[] OnEndGetPersonImage(System.IAsyncResult result) {
            byte[] retVal = this.EndGetPersonImage(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetPersonImageCompleted(object state) {
            if ((this.GetPersonImageCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPersonImageCompleted(this, new GetPersonImageCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetPersonImageAsync(string token, int idRuta, int idPerfil, int idPersona) {
            this.GetPersonImageAsync(token, idRuta, idPerfil, idPersona, null);
        }
        
        public void GetPersonImageAsync(string token, int idRuta, int idPerfil, int idPersona, object userState) {
            if ((this.onBeginGetPersonImageDelegate == null)) {
                this.onBeginGetPersonImageDelegate = new BeginOperationDelegate(this.OnBeginGetPersonImage);
            }
            if ((this.onEndGetPersonImageDelegate == null)) {
                this.onEndGetPersonImageDelegate = new EndOperationDelegate(this.OnEndGetPersonImage);
            }
            if ((this.onGetPersonImageCompletedDelegate == null)) {
                this.onGetPersonImageCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPersonImageCompleted);
            }
            base.InvokeAsync(this.onBeginGetPersonImageDelegate, new object[] {
                        token,
                        idRuta,
                        idPerfil,
                        idPersona}, this.onEndGetPersonImageDelegate, this.onGetPersonImageCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override VoyIteso.ServiceReferenceVoyItesoMovil.VoyItesoMovil CreateChannel() {
            return new VoyItesoMovilClientChannel(this);
        }
        
        private class VoyItesoMovilClientChannel : ChannelBase<VoyIteso.ServiceReferenceVoyItesoMovil.VoyItesoMovil>, VoyIteso.ServiceReferenceVoyItesoMovil.VoyItesoMovil {
            
            public VoyItesoMovilClientChannel(System.ServiceModel.ClientBase<VoyIteso.ServiceReferenceVoyItesoMovil.VoyItesoMovil> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetRouteInfo(VoyIteso.ServiceReferenceVoyItesoMovil.GetRouteInfoRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetRouteInfo", _args, callback, asyncState);
                return _result;
            }
            
            public VoyIteso.ServiceReferenceVoyItesoMovil.GetRouteInfoResponse EndGetRouteInfo(System.IAsyncResult result) {
                object[] _args = new object[0];
                VoyIteso.ServiceReferenceVoyItesoMovil.GetRouteInfoResponse _result = ((VoyIteso.ServiceReferenceVoyItesoMovil.GetRouteInfoResponse)(base.EndInvoke("GetRouteInfo", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetUserName(VoyIteso.ServiceReferenceVoyItesoMovil.GetUserNameRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetUserName", _args, callback, asyncState);
                return _result;
            }
            
            public VoyIteso.ServiceReferenceVoyItesoMovil.GetUserNameResponse EndGetUserName(System.IAsyncResult result) {
                object[] _args = new object[0];
                VoyIteso.ServiceReferenceVoyItesoMovil.GetUserNameResponse _result = ((VoyIteso.ServiceReferenceVoyItesoMovil.GetUserNameResponse)(base.EndInvoke("GetUserName", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetRouteSearchResult(VoyIteso.ServiceReferenceVoyItesoMovil.GetRouteSearchResultRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetRouteSearchResult", _args, callback, asyncState);
                return _result;
            }
            
            public VoyIteso.ServiceReferenceVoyItesoMovil.GetRouteSearchResultResponse EndGetRouteSearchResult(System.IAsyncResult result) {
                object[] _args = new object[0];
                VoyIteso.ServiceReferenceVoyItesoMovil.GetRouteSearchResultResponse _result = ((VoyIteso.ServiceReferenceVoyItesoMovil.GetRouteSearchResultResponse)(base.EndInvoke("GetRouteSearchResult", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetPersonImage(VoyIteso.ServiceReferenceVoyItesoMovil.GetPersonImageRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetPersonImage", _args, callback, asyncState);
                return _result;
            }
            
            public VoyIteso.ServiceReferenceVoyItesoMovil.GetPersonImageResponse EndGetPersonImage(System.IAsyncResult result) {
                object[] _args = new object[0];
                VoyIteso.ServiceReferenceVoyItesoMovil.GetPersonImageResponse _result = ((VoyIteso.ServiceReferenceVoyItesoMovil.GetPersonImageResponse)(base.EndInvoke("GetPersonImage", _args, result)));
                return _result;
            }
        }
    }
}
