//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoyIteso.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VoyIteso.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /aventon/{0}/aceptar.
        /// </summary>
        public static string ApiAcceptLift {
            get {
                return ResourceManager.GetString("ApiAcceptLift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /aventon/solicitar.
        /// </summary>
        public static string ApiAskForLift {
            get {
                return ResourceManager.GetString("ApiAskForLift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://voy.cocoapps.mx/VOYAPI.
        /// </summary>
        public static string ApiBaseUrl {
            get {
                return ResourceManager.GetString("ApiBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /aventon/{0}/cancelar.
        /// </summary>
        public static string ApiCancelLift {
            get {
                return ResourceManager.GetString("ApiCancelLift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ruta/crear.
        /// </summary>
        public static string ApiCreateRoute {
            get {
                return ResourceManager.GetString("ApiCreateRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /perfil/editar.
        /// </summary>
        public static string ApiEditProfile {
            get {
                return ResourceManager.GetString("ApiEditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ruta/editar.
        /// </summary>
        public static string ApiEditRoute {
            get {
                return ResourceManager.GetString("ApiEditRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /perfil/subir_imagen_perfil.
        /// </summary>
        public static string ApiEditUserPhoto {
            get {
                return ResourceManager.GetString("ApiEditUserPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ruta/{0}/eliminar.
        /// </summary>
        public static string ApiEliminateRote {
            get {
                return ResourceManager.GetString("ApiEliminateRote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /perfil/{0}/ver.
        /// </summary>
        public static string ApiGetProfile {
            get {
                return ResourceManager.GetString("ApiGetProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /perfil/aventones_mes_actual.
        /// </summary>
        public static string ApiGetProfileCurrentMonthLift {
            get {
                return ResourceManager.GetString("ApiGetProfileCurrentMonthLift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /perfil/mi_red.
        /// </summary>
        public static string ApiGetProfileHistory {
            get {
                return ResourceManager.GetString("ApiGetProfileHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /perfil/imagen/{0}.
        /// </summary>
        public static string ApiGetProfileImage {
            get {
                return ResourceManager.GetString("ApiGetProfileImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /perfil/notificaciones_sin_leer.
        /// </summary>
        public static string ApiGetProfileNewNotifications {
            get {
                return ResourceManager.GetString("ApiGetProfileNewNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /perfil/aventones_proximo_mes.
        /// </summary>
        public static string ApiGetProfileNextMonthLift {
            get {
                return ResourceManager.GetString("ApiGetProfileNextMonthLift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /perfil/notificaciones.
        /// </summary>
        public static string ApiGetProfileNotifications {
            get {
                return ResourceManager.GetString("ApiGetProfileNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /perfil/{0}/rutas.
        /// </summary>
        public static string ApiGetProfileRoutes {
            get {
                return ResourceManager.GetString("ApiGetProfileRoutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /seguridad/login.
        /// </summary>
        public static string ApiLogIn {
            get {
                return ResourceManager.GetString("ApiLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /aventon/{0}/calificar.
        /// </summary>
        public static string ApiRateLift {
            get {
                return ResourceManager.GetString("ApiRateLift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /aventon/{0}/rechazar.
        /// </summary>
        public static string ApiRejectLift {
            get {
                return ResourceManager.GetString("ApiRejectLift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /home/reportar_abuso.
        /// </summary>
        public static string ApiReportUser {
            get {
                return ResourceManager.GetString("ApiReportUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ruta/busqueda.
        /// </summary>
        public static string ApiSearchRoute {
            get {
                return ResourceManager.GetString("ApiSearchRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?security_token=.
        /// </summary>
        public static string ApiSecurityToken {
            get {
                return ResourceManager.GetString("ApiSecurityToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /home/enviar_comentario.
        /// </summary>
        public static string ApiSendComment {
            get {
                return ResourceManager.GetString("ApiSendComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /aventon/{0}/nuevomensaje.
        /// </summary>
        public static string ApiSendMessage {
            get {
                return ResourceManager.GetString("ApiSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /ruta/{0}/ver.
        /// </summary>
        public static string ApiShowRoute {
            get {
                return ResourceManager.GetString("ApiShowRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://aplicacionesweb.iteso.mx/VOYAPI.
        /// </summary>
        public static string ApiVoyItesoBaseUrl {
            get {
                return ResourceManager.GetString("ApiVoyItesoBaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY APPLICATION.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AvDQJsJmO3bo81iGaiLH9LaaqNYp28mcrzI9MFxsFPBRktl1hvNxLHe8u_uU8GTu.
        /// </summary>
        public static string BingServiceKey {
            get {
                return ResourceManager.GetString("BingServiceKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://dev.virtualearth.net/REST/v1/Locations{0}.
        /// </summary>
        public static string BingServiceUrl {
            get {
                return ResourceManager.GetString("BingServiceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Hola.
        /// </summary>
        public static string HelloUsertxt {
            get {
                return ResourceManager.GetString("HelloUsertxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
    }
}
